/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IssuesIndexRouteImport } from './routes/issues.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as IssuesIssueIdRouteImport } from './routes/issues.$issueId'
import { Route as DocsDocIdRouteImport } from './routes/docs.$docId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssueIdRoute = IssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDocIdRoute = DocsDocIdRouteImport.update({
  id: '/docs/$docId',
  path: '/docs/$docId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/docs/': typeof DocsIndexRoute
  '/issues/': typeof IssuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/docs': typeof DocsIndexRoute
  '/issues': typeof IssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/docs/': typeof DocsIndexRoute
  '/issues/': typeof IssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/docs/$docId'
    | '/issues/$issueId'
    | '/docs/'
    | '/issues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/docs/$docId'
    | '/issues/$issueId'
    | '/docs'
    | '/issues'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/docs/$docId'
    | '/issues/$issueId'
    | '/docs/'
    | '/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  DocsDocIdRoute: typeof DocsDocIdRoute
  IssuesIssueIdRoute: typeof IssuesIssueIdRoute
  DocsIndexRoute: typeof DocsIndexRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issueId': {
      id: '/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof IssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$docId': {
      id: '/docs/$docId'
      path: '/docs/$docId'
      fullPath: '/docs/$docId'
      preLoaderRoute: typeof DocsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  DocsDocIdRoute: DocsDocIdRoute,
  IssuesIssueIdRoute: IssuesIssueIdRoute,
  DocsIndexRoute: DocsIndexRoute,
  IssuesIndexRoute: IssuesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
